#sandygcabanes
#practicepython.org
#exercise 18 cows and bulls
"""Cows and Bulls Game
Exercise 18 (and Solution)
Create a program that will play the “cows and bulls” game with the user.
The game works like this: Randomly generate a 4-digit number.
Ask the user to guess a 4-digit number. For every digit that the user guessed
correctly in the correct place, they have a “cow”. For every digit the user
guessed correctly in the wrong place is a “bull.” Every time the user makes a
guess, tell them how many “cows” and “bulls” they have. Once the user guesses
the correct number, the game is over. Keep track of the number of guesses the
user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could
look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
"""

import random

def generate_random(numeric):
    """
    Generates random x-digit number digit by digit.
    Remove duplicates via set function, using 20 truncated to 4.
    numeric = x = pre-specified.
    """
    import random
    # generate a list of 20 random integers
    # to ensure final set has at least x items after duplicate removal
    i=0
    newlist = []
    while i < 20:
        item = str(random.randint(0,9))
        newlist.append(item)
        i +=1
    # using set function to eliminate duplicates
    newset = set(newlist)
    newlist2 = list(newset)
    finalist = newlist2[0:numeric] #truncate list to numeric no. of items only
    new_random_num = "".join(finalist)
    return new_random_num # need this to assign output to variable outside function

computer_list= list(generate_random(4))
#print (computer_list) #Only for testing
n = list(input("Cows and Bulls Game. Guess the four-digit number:"))
print (n)

def cows_bulls(guess,reference):

    #This starts the loop from first to fourth digit.
    #guess = 4-digit guess
    #reference = 4-digit random number generated by generate_random function

    cows = 0
    bulls = 0
    i = 0  # i is the index of the guess string and reference string
    while i < 4:
        if guess[i] == reference[i]:
            cows = cows + 1
        elif str(guess[i]) in reference:
            bulls = bulls + 1
        else:
            cows = cows
            bulls = bulls
        i += 1
    print (" {} cow/s, {} bull/s".format(cows, bulls))
    if cows == 4:
        print ("Congratulations!  You guessed it.")
    if cows != 4:
        next_try = str(input("Guess again? y/n"))
        if next_try == "Y" or "y":
            n = list(input("Input next guess, 4-digit number:"))
            print (n)
            cows_bulls(n,computer_list)
        elif next_try == "N" or "n":
            print("End of game")

cows_bulls(n, computer_list)




